### ISSUE TITLE
post about this library in reddit

### ISSUE THREAD

**Issue by Goldziher** [dkress59/wordpress-api-client#5]
Hiya,

If you want to get more stars / users, you should make a post about this library in reddit - the typescript reddit, probably also a wordpress reddit and the javascript reddit. You can use markdown in your reddit posts, so its better to write a proper post with markdown and mark it as a showcase or resource (its called a flair in reddit - and different reddits have different ones). 

Make sure to do this at morning time east coast US on sunday or monday, and read the rules of the respective subreddits first. 

Just my 2 cents.

**Comment by dkress59** [comment]
thanks for the input, man! I've really got it production-ready in the past couple of days, I'll make sure to dig into reddit before releasing v1.0 :+1:
